

# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`
i
#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`


In [6]:
#### 1. Import the numpy package under the name `np`
import numpy as np

In [11]:
#### 2. Create a null vector of size 10 
a = np.zeros((10))


In [12]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
#### 3. Create a null vector of size 10 but the fifth value which is 1
b = np.zeros((1,10))
b[0,4] = 1

In [18]:
b

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [43]:
#### 4. Create a vector with values ranging from 10 to 49

c = np.random.randint(10,50,39) 

In [45]:
print(c)
type(c)

[10 35 26 39 24 26 35 27 35 28 27 27 19 21 43 36 49 26 32 23 22 11 18 38
 32 15 46 29 44 37 33 33 15 22 39 31 12 45 13]


numpy.ndarray

In [23]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8
d = np.random.randint(0, 8, (3, 3))

In [24]:
d

array([[4, 1, 6],
       [6, 6, 0],
       [5, 6, 1]])

In [25]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0]
### method from Boolean indexing in Numpy codealong is not working here that's why nonzero method used instead
e =np.array([1,2,0,0,4,0])
np.nonzero(e)

(array([0, 1, 4]),)

In [27]:
#### 7. Create a 3x3 identity matrix
f = np.eye(3)

In [28]:
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
#### 8. Create a 3x3x3 array with random values 
g = np.random.random((3,3,3))
print(g)

[[[0.3066043  0.19425341 0.13839801]
  [0.05395813 0.56391397 0.60056654]
  [0.0455453  0.05264801 0.14776317]]

 [[0.27444952 0.53054132 0.68004266]
  [0.38388032 0.08180138 0.80498941]
  [0.46519624 0.07156367 0.36046683]]

 [[0.012314   0.77476425 0.11632289]
  [0.90764733 0.19319361 0.05058242]
  [0.72133033 0.95392441 0.81808754]]]


In [30]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values
np.random.seed(1006)
h = np.random.random((10,10))
print(h)

[[0.74312736 0.22642433 0.64253383 0.88235546 0.74069877 0.72126355
  0.29534784 0.52551637 0.17376453 0.81195921]
 [0.8494054  0.25652014 0.23723445 0.45838538 0.22892017 0.20201054
  0.98268038 0.98072856 0.73480386 0.40930499]
 [0.61881122 0.07922681 0.3992603  0.60542101 0.45048703 0.49126614
  0.36450761 0.28902666 0.99520902 0.81677776]
 [0.26502976 0.35804741 0.66968568 0.92568623 0.01828065 0.83617359
  0.20375291 0.55750424 0.88577519 0.18547542]
 [0.35751405 0.54127987 0.23651822 0.21049158 0.52448184 0.6481872
  0.24837678 0.02222478 0.1201708  0.42562707]
 [0.76399581 0.70977053 0.19941661 0.37676384 0.80578279 0.26005507
  0.10166105 0.92256783 0.03549357 0.54065812]
 [0.01723636 0.53233838 0.84360437 0.10915717 0.77826184 0.35268578
  0.6717339  0.15330277 0.06796606 0.76147119]
 [0.0727039  0.97703318 0.67623099 0.70213564 0.96799672 0.503032
  0.19283654 0.02437558 0.01272804 0.00933905]
 [0.23777199 0.32341238 0.35805865 0.63503597 0.66816687 0.23547847
  0.94025659 0.

In [31]:
h.min()

0.009339047558688862

In [32]:
h.max()

0.9952090195788573

In [46]:
#### 10. Create a random vector of size 30 and find the mean value
i = np.random.rand(30)

In [47]:
i

array([0.12983608, 0.40752709, 0.20367982, 0.7011896 , 0.26217776,
       0.63624299, 0.42128296, 0.18892164, 0.76394463, 0.31788866,
       0.11193429, 0.01490387, 0.95458222, 0.37145424, 0.80370489,
       0.35805949, 0.25777369, 0.35433876, 0.41312747, 0.60933192,
       0.81029524, 0.30609995, 0.90219201, 0.37346439, 0.97113222,
       0.80820022, 0.53770799, 0.98421162, 0.42214124, 0.64504466])

In [50]:
np.mean(i)

0.5014130532853255

In [60]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 
# create a 5x5 zero matrix
import numpy as np

# create a 5x5 zero matrix
matrix = np.zeros((5, 5), dtype=int)

# fill values just below the diagonal
for x in range(1, 5):
    for z in range(x):
        matrix[x, z] = z+1

print(matrix)





[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 2 0 0 0]
 [1 2 3 0 0]
 [1 2 3 4 0]]


In [ ]:
#### 12. Normalize a 5x5 random matrix

In [ ]:
#### 13. How to find common values between two arrays? 

In [ ]:
#### 14. Create a random vector of size 10 and sort it 

In [ ]:
#### 15. Create random vector of size 10 and replace the maximum value by 0

In [ ]:
#### 16. Subtract the mean of each row of a matrix

In [ ]:
#### 17. How to get the n largest values of an array

In [ ]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 